#!/bin/bash
# Demo script for the 2D Slice View feature
# This script shows how to use the slice view functionality

echo "═══════════════════════════════════════════════════════════"
echo "  2D Slice View Feature Demo"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This demo will show you how to use the 2D slice view feature."
echo ""
echo "Steps to try the feature:"
echo ""
echo "1. Launch the viewer with a 3MF file:"
echo "   cd /home/runner/work/lib3mf_rust/lib3mf_rust/tools/viewer"
echo "   cargo run --release -- -u ../../test_files/core/box.3mf"
echo ""
echo "2. Enable the slice view:"
echo "   - Press 'Z' to toggle the slice view ON"
echo "   - You should see:"
echo "     • Yellow rectangle showing the slice plane"
echo "     • Red lines showing where the model intersects the plane"
echo "     • Console output showing Z height and segment count"
echo ""
echo "3. Adjust the slice height:"
echo "   - Press 'Shift+Up' to move the slice plane up"
echo "   - Press 'Shift+Down' to move the slice plane down"
echo "   - The contours update in real-time"
echo ""
echo "4. Toggle the slice plane visibility:"
echo "   - Press 'L' to hide/show the yellow plane rectangle"
echo "   - The contours remain visible"
echo ""
echo "5. Export the slice to PNG:"
echo "   - Press 'X' to export the current slice"
echo "   - File will be saved with format: slice_z_<height>mm_<timestamp>.png"
echo "   - Includes coordinate grid and red contour lines"
echo ""
echo "6. Try different models:"
echo "   - Ctrl+O to open a different file"
echo "   - Or use Ctrl+T to browse test suite files"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Example with test files:"
echo ""
echo "  Box:        Simple rectangular cross-sections"
echo "  Sphere:     Circular cross-sections"
echo "  Torus:      Donut-shaped cross-sections"
echo "  Cylinder:   Circular cross-sections"
echo ""
echo "═══════════════════════════════════════════════════════════"
