#ifndef LIB3MF_FFI_H
#define LIB3MF_FFI_H

/* Generated with cbindgen:0.28.0 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result code returned by all FFI functions.
 */
enum Lib3mfResult
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    /**
     * Operation completed successfully.
     */
    Ok = 0,
    /**
     * A null pointer was passed where a valid pointer was required.
     */
    ErrorNullPointer = 1,
    /**
     * An I/O error occurred (e.g., file not found).
     */
    ErrorIo = 2,
    /**
     * The 3MF file could not be parsed.
     */
    ErrorParse = 3,
    /**
     * An index parameter was out of bounds.
     */
    ErrorIndexOutOfBounds = 4,
    /**
     * An invalid argument was provided.
     */
    ErrorInvalidArg = 5,
    /**
     * An unspecified internal error occurred.
     */
    ErrorInternal = 6,
};
#ifndef __cplusplus
typedef int32_t Lib3mfResult;
#endif // __cplusplus

/**
 * Opaque handle representing a 3MF model.
 *
 * Created by [`lib3mf_model_create`] or [`lib3mf_model_read_file`] and must
 * be freed with [`lib3mf_model_destroy`].
 */
typedef struct Lib3mfModel Lib3mfModel;

/**
 * A 3D vertex with double-precision coordinates.
 */
typedef struct Lib3mfVertex {
    double x;
    double y;
    double z;
} Lib3mfVertex;

/**
 * A triangle defined by three vertex indices.
 */
typedef struct Lib3mfTriangle {
    uint32_t v1;
    uint32_t v2;
    uint32_t v3;
} Lib3mfTriangle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to a null-terminated string describing the last error.
 *
 * The pointer is valid until the next FFI call on the same thread. If no
 * error has occurred the string is empty.
 *
 * # Safety
 *
 * The returned pointer must not be used after the next FFI call on the same thread.
 */
const char *lib3mf_get_last_error(void);

/**
 * Creates a new, empty 3MF model.
 *
 * On success, `*model_out` is set to a valid handle and `Lib3mfResult::Ok`
 * is returned. The caller must free the handle with [`lib3mf_model_destroy`].
 *
 * # Safety
 *
 * `model_out` must be a valid, non-null pointer to a `*mut Lib3mfModel`.
 */
Lib3mfResult lib3mf_model_create(struct Lib3mfModel **model_out);

/**
 * Reads a 3MF file from disk and returns a model handle.
 *
 * `path` must be a null-terminated UTF-8 string. On success, `*model_out`
 * is set to a valid handle. The caller must free it with
 * [`lib3mf_model_destroy`].
 *
 * # Safety
 *
 * `path` must be a valid, non-null pointer to a null-terminated UTF-8 string.
 * `model_out` must be a valid, non-null pointer to a `*mut Lib3mfModel`.
 */
Lib3mfResult lib3mf_model_read_file(const char *path, struct Lib3mfModel **model_out);

/**
 * Writes the model to a 3MF file on disk.
 *
 * The model handle remains valid after this call.
 * `path` must be a null-terminated UTF-8 string.
 *
 * # Safety
 *
 * `model` must be a valid handle obtained from [`lib3mf_model_create`] or
 * [`lib3mf_model_read_file`]. `path` must be a valid, non-null pointer to a
 * null-terminated UTF-8 string.
 */
Lib3mfResult lib3mf_model_write_file(const struct Lib3mfModel *model, const char *path);

/**
 * Frees a model handle previously obtained from [`lib3mf_model_create`] or
 * [`lib3mf_model_read_file`].
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `model` must be either null or a valid handle that has not already been
 * destroyed.
 */
void lib3mf_model_destroy(struct Lib3mfModel *model);

/**
 * Returns a pointer to the model's unit string (e.g. `"millimeter"`).
 *
 * The pointer is valid until the next call to this function on the same
 * thread, or until the model is destroyed.
 *
 * # Safety
 *
 * `model` must be a valid, non-null model handle. `unit_out` must be a
 * valid, non-null pointer.
 */
Lib3mfResult lib3mf_model_get_unit(const struct Lib3mfModel *model, const char **unit_out);

/**
 * Returns the number of metadata entries in the model.
 *
 * # Safety
 *
 * `model` and `count_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_metadata_count(const struct Lib3mfModel *model, uint32_t *count_out);

/**
 * Returns the name and value of a metadata entry by index.
 *
 * `name_out` and `value_out` are set to temporary string pointers that are
 * valid until the next FFI call on the same thread.
 *
 * # Safety
 *
 * `model`, `name_out`, and `value_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_metadata(const struct Lib3mfModel *model,
                                       uint32_t index,
                                       const char **name_out,
                                       const char **value_out);

/**
 * Returns the number of objects in the model.
 *
 * # Safety
 *
 * `model` and `count_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_count(const struct Lib3mfModel *model, uint32_t *count_out);

/**
 * Returns the ID of an object by its index in the object list.
 *
 * # Safety
 *
 * `model` and `id_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_id(const struct Lib3mfModel *model,
                                        uint32_t index,
                                        uint32_t *id_out);

/**
 * Returns the name of an object, or an empty string if unnamed.
 *
 * The returned pointer is valid until the next FFI call on the same thread.
 *
 * # Safety
 *
 * `model` and `name_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_name(const struct Lib3mfModel *model,
                                          uint32_t index,
                                          const char **name_out);

/**
 * Returns the number of vertices in an object's mesh.
 *
 * If the object has no mesh, `*count_out` is set to 0.
 *
 * # Safety
 *
 * `model` and `count_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_vertex_count(const struct Lib3mfModel *model,
                                                  uint32_t object_index,
                                                  uint32_t *count_out);

/**
 * Returns the number of triangles in an object's mesh.
 *
 * If the object has no mesh, `*count_out` is set to 0.
 *
 * # Safety
 *
 * `model` and `count_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_triangle_count(const struct Lib3mfModel *model,
                                                    uint32_t object_index,
                                                    uint32_t *count_out);

/**
 * Retrieves a single vertex from an object's mesh.
 *
 * # Safety
 *
 * `model` and `vertex_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_vertex(const struct Lib3mfModel *model,
                                            uint32_t object_index,
                                            uint32_t vertex_index,
                                            struct Lib3mfVertex *vertex_out);

/**
 * Retrieves a single triangle from an object's mesh.
 *
 * # Safety
 *
 * `model` and `triangle_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_object_triangle(const struct Lib3mfModel *model,
                                              uint32_t object_index,
                                              uint32_t triangle_index,
                                              struct Lib3mfTriangle *triangle_out);

/**
 * Returns the number of build items.
 *
 * # Safety
 *
 * `model` and `count_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_build_item_count(const struct Lib3mfModel *model,
                                               uint32_t *count_out);

/**
 * Returns the object ID referenced by a build item.
 *
 * # Safety
 *
 * `model` and `object_id_out` must be valid, non-null pointers.
 */
Lib3mfResult lib3mf_model_get_build_item_object_id(const struct Lib3mfModel *model,
                                                   uint32_t index,
                                                   uint32_t *object_id_out);

/**
 * Retrieves the 4×3 affine transformation matrix of a build item.
 *
 * If the build item has a transform, `*has_transform_out` is set to `true`
 * and the 12 doubles are written to `transform_out`. Otherwise
 * `*has_transform_out` is set to `false` and `transform_out` is untouched.
 *
 * `transform_out` must point to an array of at least 12 `f64` values.
 *
 * # Safety
 *
 * `model`, `transform_out`, and `has_transform_out` must be valid, non-null
 * pointers. `transform_out` must point to at least 12 contiguous `f64` values.
 */
Lib3mfResult lib3mf_model_get_build_item_transform(const struct Lib3mfModel *model,
                                                   uint32_t index,
                                                   double *transform_out,
                                                   bool *has_transform_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIB3MF_FFI_H */
